### ISSUE TITLE
compile to tsx support?

### ISSUE THREAD

**Issue by beenotung** [mistlog/typedraft#1]
The approach of using jsx to write macro seems great, but can the target output be tsx as well?
Or it's indistinguishable between the macro jsx and runtime jsx so the target must be ts?

Extracted from https://github.com/mistlog/typedraft-docs/commit/ff3826783159d5b5adafdc4b3c6915b7eb21b839#r37077393

**Comment by mistlog** [comment]
# Target tsx
Yes, we can, maybe we can add something like config file and specify the target extension you want. For example, something like tsconfig.json:

```json
{
   "compilerOptions":{
     "target": "tsx"
   }
}
```

# Macro jsx and runtime jsx

We can differentiate macro jsx from runtime jsx because the algorithm is that:

1. scan the file and find function declaration, eg.
```typescript
function Test(){
}
```
2. iterate the usage of the function
3. if it's used as standalone statement, such as
```typescript
...
<Test/>; 
...
```
then it's macro jsx, or what we called ```local context```

implementation here: https://github.com/mistlog/typedraft/blob/master/src/code-object/module.tsx#L159

we will not mix it up with runtime jsx because if we want to use a component, we will not use it as a *standalone* statement, as it doesn't produce output or contribute to the UI.

**Comment by beenotung** [comment]
Thanks for your detailed answer, I think we can close this issue
